#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由包 BD.Common.Repositories.SourceGenerator 源生成。
//     运行时版本：4.8.9139.0
//     编译器版本：4.6.0-3.23259.8 (c3cc1d0c)
//     生成器版本：1.23.10613.11400 (c239958a)
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable once CheckNamespace
namespace BD.Common.Repositories.SourceGenerator.ConsoleTest.Models;

/// <summary>
/// 示例 - 后台管理添加模型
/// </summary>
public sealed partial class AddExampleDTO : ITitle, IDisable, IDescribe, IDisableReason, IGender, INickName, IOrder, IIsTop, IIPAddress, IPassword, IRemarks, ISmsCode
{
    /// <summary>
    /// 标题
    /// </summary>
    [Required]
    public string Title { get; set; } = "";

    /// <summary>
    /// 是否禁用
    /// </summary>
    public bool Disable { get; set; }

    /// <summary>
    /// 文件名
    /// </summary>
    [MaxLength(255, ErrorMessage = "AAAA")]
    [StringLength(35, ErrorMessage = "BBBB")]
    public string? FileName { get; set; }

    /// <summary>
    /// 访问地址
    /// </summary>
    [MaxLength(2048)]
    public string? Url { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [Required]
    [StringLength(35, MinimumLength = 1, ErrorMessage = "D")]
    public string Name { get; set; } = "";

    /// <summary>
    /// 平均分
    /// </summary>
    public float AverageScore { get; set; }

    /// <summary>
    /// 平均分 2
    /// </summary>
    public float AverageScore2 { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    [EmailAddress]
    [Required]
    public string Email { get; set; } = "";

    /// <summary>
    /// Architecture
    /// </summary>
    public Architecture Architecture { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    public string? Describe { get; set; }

    /// <summary>
    /// 禁用原因
    /// </summary>
    public string? DisableReason { get; set; }

    /// <summary>
    /// 性别
    /// </summary>
    public Gender Gender { get; set; }

    /// <summary>
    /// 昵称
    /// </summary>
    public string? NickName { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public long Order { get; set; }

    /// <summary>
    /// 是否置顶
    /// </summary>
    public bool IsTop { get; set; }

    /// <summary>
    /// IP 地址
    /// </summary>
    [Required]
    public string IPAddress { get; set; } = "";

    /// <summary>
    /// 密码
    /// </summary>
    [Required]
    public string Password { get; set; } = "";

    /// <summary>
    /// 备注
    /// </summary>
    public string? Remarks { get; set; }

    /// <summary>
    /// 短信验证码
    /// </summary>
    public string? SmsCode { get; set; }
}

/// <summary>
/// 示例 - 后台管理编辑模型
/// </summary>
public sealed partial class EditExampleDTO : IDescribe, IDisableReason, IGender, INickName, IOrder, IIsTop, IIPAddress, IPassword, IRemarks, ISmsCode
{
    /// <summary>
    /// 文件名
    /// </summary>
    [MaxLength(255, ErrorMessage = "AAAA")]
    [StringLength(35, ErrorMessage = "BBBB")]
    public string? FileName { get; set; }

    /// <summary>
    /// 访问地址
    /// </summary>
    [MaxLength(2048)]
    public string? Url { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [Required]
    [StringLength(35, MinimumLength = 1, ErrorMessage = "D")]
    public string Name { get; set; } = "";

    /// <summary>
    /// 平均分
    /// </summary>
    public float AverageScore { get; set; }

    /// <summary>
    /// 平均分 2
    /// </summary>
    public float AverageScore2 { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    [EmailAddress]
    [Required]
    public string Email { get; set; } = "";

    /// <summary>
    /// Architecture
    /// </summary>
    public Architecture Architecture { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    public string? Describe { get; set; }

    /// <summary>
    /// 禁用原因
    /// </summary>
    public string? DisableReason { get; set; }

    /// <summary>
    /// 性别
    /// </summary>
    public Gender Gender { get; set; }

    /// <summary>
    /// 昵称
    /// </summary>
    public string? NickName { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public long Order { get; set; }

    /// <summary>
    /// 是否置顶
    /// </summary>
    public bool IsTop { get; set; }

    /// <summary>
    /// IP 地址
    /// </summary>
    [Required]
    public string IPAddress { get; set; } = "";

    /// <summary>
    /// 密码
    /// </summary>
    [Required]
    public string Password { get; set; } = "";

    /// <summary>
    /// 备注
    /// </summary>
    public string? Remarks { get; set; }

    /// <summary>
    /// 短信验证码
    /// </summary>
    public string? SmsCode { get; set; }
}

/// <summary>
/// 示例 - 后台管理表格查询模型
/// </summary>
public sealed partial class TableExampleDTO : IKeyModel<Guid>, ITitle, IDisable, ICreateUserIdNullable, ICreationTime, IOperatorUserId, IDescribe, IDisableReason, IGender, INickName, IOrder, IIsTop, IIPAddress, IPassword, IRemarks, ISmsCode
{
    /// <summary>
    /// 主键
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 标题
    /// </summary>
    [Required]
    public string Title { get; set; } = "";

    /// <summary>
    /// 是否禁用
    /// </summary>
    public bool Disable { get; set; }

    /// <summary>
    /// 文件名
    /// </summary>
    [MaxLength(255, ErrorMessage = "AAAA")]
    [StringLength(35, ErrorMessage = "BBBB")]
    public string? FileName { get; set; }

    /// <summary>
    /// 访问地址
    /// </summary>
    [MaxLength(2048)]
    public string? Url { get; set; }

    /// <summary>
    /// 创建人 UserId（创建此条目的后台管理员）
    /// </summary>
    public Guid? CreateUserId { get; set; }

    /// <summary>
    /// 创建人（创建此条目的后台管理员）
    /// </summary>
    public string? CreateUser { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTimeOffset CreationTime { get; set; }

    /// <summary>
    /// 最后一次操作的人 UserId（记录后台管理员禁用或启用或编辑该条的操作）
    /// </summary>
    public Guid? OperatorUserId { get; set; }

    /// <summary>
    /// 最后一次操作的人（记录后台管理员禁用或启用或编辑该条的操作）
    /// </summary>
    public string? OperatorUser { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [Required]
    [StringLength(35, MinimumLength = 1, ErrorMessage = "D")]
    public string Name { get; set; } = "";

    /// <summary>
    /// 平均分
    /// </summary>
    public float AverageScore { get; set; }

    /// <summary>
    /// 平均分 2
    /// </summary>
    public float AverageScore2 { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    [EmailAddress]
    [Required]
    public string Email { get; set; } = "";

    /// <summary>
    /// Architecture
    /// </summary>
    public Architecture Architecture { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    public string? Describe { get; set; }

    /// <summary>
    /// 禁用原因
    /// </summary>
    public string? DisableReason { get; set; }

    /// <summary>
    /// 性别
    /// </summary>
    public Gender Gender { get; set; }

    /// <summary>
    /// 昵称
    /// </summary>
    public string? NickName { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public long Order { get; set; }

    /// <summary>
    /// 是否置顶
    /// </summary>
    public bool IsTop { get; set; }

    /// <summary>
    /// IP 地址
    /// </summary>
    [Required]
    public string IPAddress { get; set; } = "";

    /// <summary>
    /// 密码
    /// </summary>
    [Required]
    public string Password { get; set; } = "";

    /// <summary>
    /// 备注
    /// </summary>
    public string? Remarks { get; set; }

    /// <summary>
    /// 短信验证码
    /// </summary>
    public string? SmsCode { get; set; }
}

