#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由包 BD.Common.Repositories.SourceGenerator 源生成。
//     运行时版本：4.8.9139.0
//     编译器版本：4.6.0-3.23259.8 (c3cc1d0c)
//     生成器版本：1.23.10613.11400 (c239958a)
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable once CheckNamespace
namespace BD.Common.Repositories.SourceGenerator.ConsoleTest.Entities;

/// <summary>
/// 示例 - 表实体模型
/// </summary>
[Table("Examples")]
public sealed partial class Example : TenantBaseEntityV2<Guid>, ITitle, IDisable, IDescribe, IDisableReason, IGender, INickName, IOrder, IIsTop, IIPAddress, IPassword, IRemarks, ISmsCode, INEWSEQUENTIALID
{
    /// <summary>
    /// 主键
    /// </summary>
    [Comment("主键")]
    [Key]
    public override Guid Id { get; set; }

    /// <summary>
    /// 标题
    /// </summary>
    [Comment("标题")]
    [Required]
    public string Title { get; set; } = "";

    /// <summary>
    /// 是否禁用
    /// </summary>
    [Comment("是否禁用")]
    public bool Disable { get; set; }

    #region CloudFileInfo

    /// <summary>
    /// 文件名
    /// </summary>
    [MaxLength(255, ErrorMessage = "AAAA")]
    [Comment("xxxx")]
    [StringLength(35, ErrorMessage = "BBBB")]
    public string? FileName { get; set; }

    /// <summary>
    /// SHA256
    /// </summary>
    [MaxLength(67)]
    [MinLength(64)]
    [Comment("SHA256")]
    public string? SHA256 { get; set; }

    /// <summary>
    /// SHA384
    /// </summary>
    [MaxLength(99)]
    [MinLength(96)]
    [Comment("SHA384")]
    public string? SHA384 { get; set; }

    /// <summary>
    /// 文件路径
    /// </summary>
    [Url]
    [MaxLength(2048)]
    [Comment("文件路径")]
    public string? FilePath { get; set; }

    /// <summary>
    /// 文件后缀名
    /// </summary>
    [MaxLength(16)]
    [Comment("文件后缀名")]
    public string? FileExtension { get; set; }

    /// <summary>
    /// 文件类型
    /// </summary>
    [Comment("文件类型")]
    public byte FileType { get; set; }

    /// <summary>
    /// 文件大小
    /// </summary>
    [Range(0, 2147483647)]
    [Comment("文件大小")]
    public long FileSize { get; set; }

    /// <summary>
    /// 文件大小 2
    /// </summary>
    [Range(0.5, 2147483647)]
    [Comment("文件大小 2")]
    public long FileSize2 { get; set; }

    /// <summary>
    /// 文件大小 3
    /// </summary>
    [Range(typeof(double), "0.25", "2555.2")]
    [Comment("文件大小 3")]
    public double FileSize3 { get; set; }

    #endregion

    /// <summary>
    /// 访问地址
    /// </summary>
    [MaxLength(2048)]
    [Comment("访问地址")]
    public string? Url { get; set; }

    /// <summary>
    /// TestConst
    /// </summary>
    [Comment("TestConst")]
    public int TestConst { get; set; } = 1;

    /// <summary>
    /// 名称
    /// </summary>
    [Required]
    [StringLength(35, MinimumLength = 1, ErrorMessage = "D")]
    [Comment("名称")]
    public string Name { get; set; } = "";

    /// <summary>
    /// Key
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [Comment("Key")]
    public Guid Key { get; set; }

    /// <summary>
    /// 平均分
    /// </summary>
    [Precision(5, 2)]
    [Comment("平均分")]
    public float AverageScore { get; set; }

    /// <summary>
    /// 平均分 2
    /// </summary>
    [Precision(5)]
    [Comment("平均分 2")]
    public float AverageScore2 { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    [EmailAddress]
    [Comment("邮箱")]
    [Required]
    public string Email { get; set; } = "";

    /// <summary>
    /// Architecture
    /// </summary>
    [Comment("Architecture")]
    public Architecture Architecture { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    [Comment("描述")]
    public string? Describe { get; set; }

    /// <summary>
    /// 禁用原因
    /// </summary>
    [Comment("禁用原因")]
    public string? DisableReason { get; set; }

    /// <summary>
    /// 性别
    /// </summary>
    [Comment("性别")]
    public Gender Gender { get; set; }

    /// <summary>
    /// 昵称
    /// </summary>
    [Comment("昵称")]
    public string? NickName { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    [Comment("排序")]
    public long Order { get; set; }

    /// <summary>
    /// 是否置顶
    /// </summary>
    [Comment("是否置顶")]
    public bool IsTop { get; set; }

    /// <summary>
    /// IP 地址
    /// </summary>
    [Comment("IP 地址")]
    [Required]
    public string IPAddress { get; set; } = "";

    /// <summary>
    /// 密码
    /// </summary>
    [Comment("密码")]
    [Required]
    public string Password { get; set; } = "";

    /// <summary>
    /// 备注
    /// </summary>
    [Comment("备注")]
    public string? Remarks { get; set; }

    /// <summary>
    /// 短信验证码
    /// </summary>
    [Comment("短信验证码")]
    public string? SmsCode { get; set; }
}

