<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<Description>适用于客户端的 HttpClient 工厂的服务端兼容实现库 (与 Microsoft.Extensions.Http 兼容)</Description>
	</PropertyGroup>

	<Import Project="$(MSBuildThisFileDirectory)..\TFM_NETX_ALL.props" />

	<!-- 👇 引用 NuGet 包 -->
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Http.ClientFactory\BD.Common8.Http.ClientFactory.csproj" />
	</ItemGroup>

</Project>
