<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<Description>仓储层 sqlite-net-pcl 实现库</Description>
	</PropertyGroup>

	<Import Project="$(MSBuildThisFileDirectory)..\TFM_NETX_ALL.props" />

	<!-- 👇 引用 NuGet 包 -->
	<ItemGroup>
		<PackageReference Include="sqlite-net-pcl" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Repositories\BD.Common8.Repositories.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Security\BD.Common8.Security.csproj" />
	</ItemGroup>

</Project>
