<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>BD.Common8.SourceGenerator.Ipc</RootNamespace>
		<TargetFramework>net$(DotNet_Version)</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\ProjectUtils.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\Ipc.Server.Sample.Experimental\ITodoService.cs">
			<LinkBase>Services</LinkBase>
		</Compile>
	</ItemGroup>

	<!-- 👇 项目引用源生成器 -->
	<ItemGroup>
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.SourceGenerator.Ipc.Client\BD.Common8.SourceGenerator.Ipc.Client.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Ipc.Client\BD.Common8.Ipc.Client.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Ipc\BD.Common8.Ipc.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Primitives\BD.Common8.Primitives.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Primitives.ApiRsp\BD.Common8.Primitives.ApiRsp.csproj" />
	</ItemGroup>
	
</Project>
