<Project>
	<Import Condition="Exists('$(MSBuildThisFileDirectory)..\..\Shared\GlobalUsings.$(MSBuildThisFileName).props')" Project="$(MSBuildThisFileDirectory)..\..\Shared\GlobalUsings.$(MSBuildThisFileName).props" />
	<ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)..\..\Shared\GlobalUsings.$(MSBuildThisFileName).props')">
		<None Condition="$(MSBuildProjectName) != $(MSBuildThisFileName)" Include="$(MSBuildThisFileDirectory)..\..\Shared\GlobalUsings.$(MSBuildThisFileName).props">
			<LinkBase>Properties\GlobalUsings</LinkBase>
		</None>
		<None Condition="$(MSBuildProjectName) == $(MSBuildThisFileName)" Include="$(MSBuildThisFileDirectory)..\..\Shared\GlobalUsings.$(MSBuildThisFileName).props">
			<LinkBase>Properties</LinkBase>
		</None>
	</ItemGroup>
	<PropertyGroup>
		<!-- 👇 Common 库引用 -->
		<BeyondDimensionFeatures>
			$(BeyondDimensionFeatures)
			BD.Common8.Bcl;
			BD.Common8.Primitives;
			BD.Common8.Primitives.ApiRsp;
		</BeyondDimensionFeatures>
		<!-- 👇 包引用（属性） -->
	</PropertyGroup>
	<ItemGroup>
		<!-- 👇 包引用 -->
		<PackageReference Include="fusillade" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
	</ItemGroup>
</Project>