<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>BD.Common8.SourceGenerator.Ipc</RootNamespace>
		<TargetFramework>net$(DotNet_Version)</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\ProjectUtils.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\Ipc.Server.Sample.Experimental\ITodoService.cs">
			<LinkBase>Services</LinkBase>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Ipc.Sample" />
	</ItemGroup>

	<!-- 👇 项目引用源生成器 -->
	<ItemGroup>
		<ProjectReference Include="$(MSBuildThisFileDirectory)..\BD.Common8.SourceGenerator.Ipc.Server\BD.Common8.SourceGenerator.Ipc.Server.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
		<ProjectReference Include="..\BD.Common8.Ipc.Server\BD.Common8.Ipc.Server.csproj" />
		<ProjectReference Include="..\BD.Common8.Ipc\BD.Common8.Ipc.csproj" />
		<ProjectReference Include="..\BD.Common8.Primitives\BD.Common8.Primitives.csproj" />
		<ProjectReference Include="..\BD.Common8.Primitives.ApiRsp\BD.Common8.Primitives.ApiRsp.csproj" />
	</ItemGroup>

</Project>
