<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net$(DotNet_Version)</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">net$(DotNet_Version);net$(DotNet_Version)-windows$(WinSDK_Version)</TargetFrameworks>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<UserSecretsId>3ca41323-7e26-4b3e-8730-2e839c58c39c</UserSecretsId>
	</PropertyGroup>

	<!-- 👇 单元测试无需 AOT & Trimmable -->
	<PropertyGroup>
		<IsTrimmable>false</IsTrimmable>
		<EnableTrimAnalyzer>false</EnableTrimAnalyzer>
		<EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
		<EnableAotAnalyzer>false</EnableAotAnalyzer>
		<IsAotCompatible>false</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
		<!--<Compile Include="..\ProjectUtils.cs" />-->
		<Compile Include="..\BD.Common8.Security\Helpers\SecurityPlatformHelper.MacOS.cs">
			<LinkBase>_SourceReference\Helpers</LinkBase>
		</Compile>
	</ItemGroup>

	<Choose>
		<When Condition="Exists('..\..\..\Constants.Sms.cs')">
			<ItemGroup>
				<Compile Remove="Constants.Sms.cs" />
				<Compile Include="..\..\..\Constants.Sms.cs" />
			</ItemGroup>
		</When>
		<When Condition="Exists('$(MSBuildThisFileDirectory)..\..\..\..\.gitmodules') AND Exists('$(MSBuildThisFileDirectory)..\..\..\..\..\Constants.Sms.cs')">
			<ItemGroup>
				<Compile Remove="Constants.Sms.cs" />
				<Compile Include="$(MSBuildThisFileDirectory)..\..\..\..\..\Constants.Sms.cs" />
			</ItemGroup>
		</When>
	</Choose>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
		<Using Include="NUnit.Framework.Interfaces" />
		<Using Include="NUnit.Framework.Internal" />
		<Using Include="NUnit.Framework.Internal.Commands" />
		<Using Include="BD.Common8.UnitTest" />
		<Using Include="BD.Common8.UnitTest.Models" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter" />
		<PackageReference Include="NUnit.Analyzers" />
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="MonoMac.NetStandard" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="System.IO.Hashing" />
		<PackageReference Include="Crc32.NET" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
	  <ProjectReference Include="..\BD.Common8.Crawler\BD.Common8.Crawler.csproj" />
	  <ProjectReference Include="..\BD.Common8.Essentials.Implementation.Avalonia\BD.Common8.Essentials.Implementation.Avalonia.csproj" />
	  <ProjectReference Include="..\BD.Common8.Essentials.Implementation\BD.Common8.Essentials.Implementation.csproj" />
	  <ProjectReference Include="..\BD.Common8.Essentials\BD.Common8.Essentials.csproj" />
	  <ProjectReference Include="..\BD.Common8.Http.ClientFactory\BD.Common8.Http.ClientFactory.csproj" />
	  <ProjectReference Include="..\BD.Common8.HuaweiCloud.SDK.Obs\BD.Common8.HuaweiCloud.SDK.Obs.csproj" />
	  <ProjectReference Include="..\BD.Common8.Ipc.Client\BD.Common8.Ipc.Client.csproj" />
	  <ProjectReference Include="..\BD.Common8.Ipc.Server\BD.Common8.Ipc.Server.csproj" />
	  <ProjectReference Include="..\BD.Common8.Ipc\BD.Common8.Ipc.csproj" />
	  <ProjectReference Include="..\BD.Common8.Orm.EFCore\BD.Common8.Orm.EFCore.csproj" />
	  <ProjectReference Include="..\BD.Common8.Pinyin.ChnCharInfo\BD.Common8.Pinyin.ChnCharInfo.csproj" />
	  <ProjectReference Include="..\BD.Common8.Pinyin\BD.Common8.Pinyin.csproj" />
	  <ProjectReference Include="..\BD.Common8.Primitives.ApiResponse\BD.Common8.Primitives.ApiResponse.csproj" />
	  <ProjectReference Include="..\BD.Common8.Primitives.District\BD.Common8.Primitives.District.csproj" />
	  <ProjectReference Include="..\BD.Common8.Primitives.Essentials\BD.Common8.Primitives.Essentials.csproj" />
	  <ProjectReference Include="..\BD.Common8.Primitives.PersonalData.BirthDate\BD.Common8.Primitives.PersonalData.BirthDate.csproj" />
	  <ProjectReference Include="..\BD.Common8.Primitives.PersonalData.PhoneNumber\BD.Common8.Primitives.PersonalData.PhoneNumber.csproj" />
	  <ProjectReference Include="..\BD.Common8.Primitives.PersonalData.UserName\BD.Common8.Primitives.PersonalData.UserName.csproj" />
	  <ProjectReference Include="..\BD.Common8.Primitives.Toast\BD.Common8.Primitives.Toast.csproj" />
	  <ProjectReference Include="..\BD.Common8.Primitives\BD.Common8.Primitives.csproj" />
	  <ProjectReference Include="..\BD.Common8.Repositories.EFCore\BD.Common8.Repositories.EFCore.csproj" />
	  <ProjectReference Include="..\BD.Common8.Repositories.SQLitePCL\BD.Common8.Repositories.SQLitePCL.csproj" />
	  <ProjectReference Include="..\BD.Common8.Repositories\BD.Common8.Repositories.csproj" />
	  <ProjectReference Include="..\BD.Common8.Security\BD.Common8.Security.csproj" />
	  <ProjectReference Include="..\BD.Common8.Settings5\BD.Common8.Settings5.csproj" />
	  <ProjectReference Include="..\BD.Common8.SmsSender\BD.Common8.SmsSender.csproj" />
	  <ProjectReference Aliases="SG_Repo" Include="..\BD.Common8.SourceGenerator.Repositories\BD.Common8.SourceGenerator.Repositories.csproj" />
	  <ProjectReference Include="..\BD.Common8.Toast\BD.Common8.Toast.csproj" />
	  <ProjectReference Include="..\BD.Common8.UserInput.ModelValidator\BD.Common8.UserInput.ModelValidator.csproj" />
	  <ProjectReference Include="..\Tools.Build\Tools.Build.csproj" />
	</ItemGroup>

</Project>
