<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<RootNamespace>System</RootNamespace>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Description>提供对基类库的扩展</Description>
	</PropertyGroup>

	<Import Project="$(MSBuildThisFileDirectory)..\TFM_NETX_ALL.props" />

	<!-- 👇 引用 NuGet 包 -->
	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="System.Text.Json" />
		<PackageReference Include="System.Net.Http.Json" />
		<PackageReference Include="Polly" />
		<PackageReference Include="Nito.Comparers" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="DotNext" />
		<PackageReference Include="DotNext.Threading" />
		<PackageReference Include="MemoryPack" />
		<PackageReference Include="MemoryPack.Streaming" />
		<PackageReference Include="MessagePack" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="System.IO.Pipelines" />
		<PackageReference Include="CommunityToolkit.HighPerformance" />
		<PackageReference Include="gfoidl.Base64" />
	</ItemGroup>

	<!-- 👇 CsWin32 源生成的 Win32 P/Invoke 函数 -->
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<PackageReference Include="Microsoft.Windows.CsWin32">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<AdditionalFiles Condition="Exists('$(MSBuildProjectDirectory)\NativeMethods.txt')" Include="$(MSBuildProjectDirectory)\NativeMethods.txt" />
		<Using Alias="CsWin32" Include="Windows.Win32" />
	</ItemGroup>

	<!-- 👇 项目引用源生成器 -->
	<ItemGroup>
		<ProjectReference Include="$(MSBuildThisFileDirectory)..\BD.Common8.SourceGenerator.ResX\BD.Common8.SourceGenerator.ResX.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="$(MSBuildThisFileDirectory)..\BD.Common8.SourceGenerator.Bcl\BD.Common8.SourceGenerator.Bcl.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

</Project>
