<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<RootNamespace>BD.Common8.Ipc</RootNamespace>
		<TargetFramework>net$(DotNet_Version)</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Description>进程间通信 (IPC) 服务端库</Description>
	</PropertyGroup>

	<!-- 👇 引用 NuGet 包 -->
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Ipc\BD.Common8.Ipc.csproj" />
	</ItemGroup>

</Project>
