<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<RootNamespace>BD.Common8.Essentials</RootNamespace>
		<Description>Avalonia UI 相关的 Essentials 实现服务库</Description>
	</PropertyGroup>

	<Import Project="$(MSBuildThisFileDirectory)..\TFM_NETX_ALL.props" />

	<!-- 👇 引用 NuGet 包 -->
	<ItemGroup>
		<PackageReference Include="Avalonia" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
		<ProjectReference Include="..\BD.Common8.Essentials\BD.Common8.Essentials.csproj" />
		<ProjectReference Include="..\BD.Common8.Essentials.Implementation\BD.Common8.Essentials.Implementation.csproj" />
	</ItemGroup>

</Project>
