<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<!--8.yy.1MMdd.1hhmm-->
		<Version>8.25.10520.12000</Version>
		<FileVersion>$(Version)</FileVersion>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<Description>基类库源生成器</Description>
	</PropertyGroup>

	<!-- 👇 基于 Attribute 生成的 Attribute 类型源码引用 -->
	<ItemGroup>
		<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Runtime\CompilerServices\*GeneratedAttribute.cs">
			<LinkBase>_SourceReference\BD.Common8.Bcl\Runtime</LinkBase>
		</Compile>
		<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Settings5\Infrastructure\*GeneratedAttribute.cs">
			<LinkBase>_SourceReference\BD.Common8.Settings5\Infrastructure</LinkBase>
		</Compile>
	</ItemGroup>

	<!-- 👇 引用 NuGet 包 -->
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Costura.Fody">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<Import Project="$(MSBuildThisFileDirectory)..\SharedProject\SourceGenerator.props" />
	
</Project>
