//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BD.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 内容值不能为空或不正确 的本地化字符串。
        /// </summary>
        internal static string 内容值不能为空或不正确 {
            get {
                return ResourceManager.GetString("内容值不能为空或不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称最大长度不能超过{0}个字 的本地化字符串。
        /// </summary>
        internal static string 昵称最大长度不能超过_ {
            get {
                return ResourceManager.GetString("昵称最大长度不能超过_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信验证码不正确 的本地化字符串。
        /// </summary>
        internal static string 短信验证码不正确 {
            get {
                return ResourceManager.GetString("短信验证码不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入手机号码哦 的本地化字符串。
        /// </summary>
        internal static string 请输入手机号码哦 {
            get {
                return ResourceManager.GetString("请输入手机号码哦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入昵称 的本地化字符串。
        /// </summary>
        internal static string 请输入昵称 {
            get {
                return ResourceManager.GetString("请输入昵称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的手机号码哦 的本地化字符串。
        /// </summary>
        internal static string 请输入正确的手机号码哦 {
            get {
                return ResourceManager.GetString("请输入正确的手机号码哦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入短信验证码哦 的本地化字符串。
        /// </summary>
        internal static string 请输入短信验证码哦 {
            get {
                return ResourceManager.GetString("请输入短信验证码哦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择头像 的本地化字符串。
        /// </summary>
        internal static string 请选择头像 {
            get {
                return ResourceManager.GetString("请选择头像", resourceCulture);
            }
        }
    }
}
