<Project>
	<!-- 📄 源生成器项目引用配置 -->

	<!-- 👇 .NET Standard，引用 Compat 兼容 CoreCLR/.NET 5+ 提供的 BCL API -->
	<ItemGroup>
		<!--<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl.Compat\**\*.cs">
			<LinkBase>_SourceReference\Compat</LinkBase>
		</Compile>
		<Compile Remove="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl.Compat\bin\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl.Compat\obj\**" />-->
		<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Extensions\StreamExtensions.Write.cs">
			<LinkBase>_SourceReference\Extensions</LinkBase>
		</Compile>
		<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Extensions\StreamExtensions.Format.cs">
			<LinkBase>_SourceReference\Extensions</LinkBase>
		</Compile>
		<!--<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Extensions\StringExtensions.Format.cs">
			<LinkBase>_SourceReference\Extensions</LinkBase>
		</Compile>-->
		<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Extensions\StringExtensions.Trim.cs">
			<LinkBase>_SourceReference\Extensions</LinkBase>
		</Compile>
		<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Extensions\StringExtensions.OICEquals.cs">
			<LinkBase>_SourceReference\Extensions</LinkBase>
		</Compile>
		<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Extensions\StringExtensions.NumberLetter.cs">
			<LinkBase>_SourceReference\Extensions</LinkBase>
		</Compile>
		<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Extensions\ObjectExtensions.ThrowIsNull.cs">
			<LinkBase>_SourceReference\Extensions</LinkBase>
		</Compile>
		<!--<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\ThrowHelper*.cs">
			<LinkBase>_SourceReference</LinkBase>
		</Compile>-->
		<!--<Compile Include="$(MSBuildThisFileDirectory)..\BD.Common8.Bcl\Resources\SR.cs">
			<LinkBase>_SourceReference\Resources</LinkBase>
		</Compile>-->
	</ItemGroup>

	<!-- 👇 .NET Compiler Platform (Roslyn) 分析器 -->
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
	</ItemGroup>

	<!-- 👇 全局命名空间引用 -->
	<Import Project="$(MSBuildThisFileDirectory)..\Shared\GlobalUsings.Microsoft.CodeAnalysis.props" />
	<Import Project="$(MSBuildThisFileDirectory)..\Shared\GlobalUsings.SourceGenerator.props" />
	<Import Project="$(MSBuildThisFileDirectory)..\Shared\GlobalUsings.System.Collections.Immutable.props" />
</Project>