<Project>
	<!-- 📄 全局属性配置 -->

	<!-- 👇 基础配置 -->
	<Import Project="$(MSBuildThisFileDirectory)Global.Base.props" />

	<!-- 👇 版本号配置 -->
	<Import Project="$(MSBuildThisFileDirectory)..\Version.props" />

	<!-- 👇 全局属性 -->
	<PropertyGroup>
		<AndroidSdkDirectory Condition="$([MSBuild]::IsOSPlatform('windows')) And Exists('C:\Users\Aigio\AppData\Local\Android\Sdk')">C:\Users\Aigio\AppData\Local\Android\Sdk</AndroidSdkDirectory>
		<NeutralLanguage>zh-Hans</NeutralLanguage>
		<Version>$(Version_Common8Bcl)</Version>
		<PackageIconUrl>https://avatars.githubusercontent.com/u/79355691</PackageIconUrl>
		<RepositoryType>git</RepositoryType>
		<Company>江苏蒸汽凡星科技有限公司</Company>
		<Copyright>©️ $(Company). All rights reserved.</Copyright>
		<Authors>$(Company)</Authors>
		<FileVersion>$(Version)</FileVersion>
		<AssemblyVersion>$(Version)</AssemblyVersion>
	</PropertyGroup>

	<!-- 👇 静态本机编译 & 剪裁 | AOT & Trimmable -->
	<PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">
		<IsTrimmable>true</IsTrimmable>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<!-- 👇 源代码分析 | Code Style -->
	<ItemGroup>
		<!--<PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />-->
	</ItemGroup>
</Project>