<Project>
	<!-- 📄 全局属性基础配置 -->

	<!-- 👇 全局属性 -->
	<PropertyGroup>
		<Deterministic>true</Deterministic>
		<!--<LangVersion>latest</LangVersion>-->
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<UseArtifactsOutput Condition="!Exists('$(MSBuildThisFileDirectory)..\..\..\.nupkg.metadata')">true</UseArtifactsOutput>
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
		<NoWarn>$(NoWarn);NU1504;NU1507;MSB4011;NU5048;NU5104</NoWarn>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<ImplicitUsings Condition="!$(TargetFramework.StartsWith('net35'))">true</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<CompilerVisibleProperty Include="Deterministic" />
	</ItemGroup>

	<!-- 👇 全局 using | Global usings -->
	<Import Condition="$(NoImplicitUsingBcl) != 'true'" Project="$(MSBuildThisFileDirectory)..\Shared\GlobalUsings.Bcl.props" />
</Project>