<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net$(DotNet_Version)</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\BD.Common8.Bcl\CodeDom\Compiler\ResXGeneratedCodeAttribute.cs">
			<LinkBase>_SourceReference\BD.Common8.Bcl\CodeDom\Compiler</LinkBase>
		</Compile>
		<Compile Include="..\BD.Common8.Bcl\CodeDom\Compiler\BinaryResourceAttribute.cs">
			<LinkBase>_SourceReference\BD.Common8.Bcl\CodeDom\Compiler</LinkBase>
		</Compile>
		<Compile Include="..\BD.Common8.Bcl\Extensions\StreamExtensions.Write.cs">
			<LinkBase>_SourceReference\BD.Common8.Bcl\Extensions</LinkBase>
		</Compile>
		<Compile Include="..\BD.Common8.Bcl\Extensions\StreamExtensions.Format.cs">
			<LinkBase>_SourceReference\BD.Common8.Bcl\Extensions</LinkBase>
		</Compile>
		<Compile Include="..\BD.Common8.SourceGenerator.ResX\Helpers\ResxSatelliteAssemblyHelper.cs">
			<LinkBase>_SourceReference\BD.Common8.Bcl\Helpers</LinkBase>
		</Compile>
		<Compile Include="..\BD.Common8.SourceGenerator.ResX\Constants.GetDefaultNamespaceByProjectName.cs">
			<LinkBase>_SourceReference\BD.Common8.SourceGenerator.ResX</LinkBase>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<!-- 👇 Resx 源生成器 -->
		<ProjectReference Include="$(MSBuildThisFileDirectory)..\BD.Common8.SourceGenerator.ResX\BD.Common8.SourceGenerator.ResX.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>
</Project>
