<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net$(DotNet_Version)</TargetFramework>
		<RootNamespace>BD.Common8.NativeHost</RootNamespace>
		<PublishAot>true</PublishAot>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AssemblyName>NativeHost</AssemblyName>
		<PublishTrimmed>true</PublishTrimmed>
	</PropertyGroup>

	<ItemGroup>
		<TrimmerRootAssembly Include="$(AssemblyName)" />
	</ItemGroup>

	<!-- 👇 CsWin32 源生成的 Win32 P/Invoke 函数 -->
	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.CsWin32">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<AdditionalFiles Condition="Exists('$(MSBuildProjectDirectory)\NativeMethods.txt')" Include="$(MSBuildProjectDirectory)\NativeMethods.txt" />
		<Using Alias="CsWin32" Include="Windows.Win32" />
		<Using Include="Windows.Win32" />
		<Using Include="Windows.Win32.Foundation" />
		<Using Include="Windows.Win32.System.ClrHosting" />
		<Using Include="Windows.Win32.System.Variant" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\ProjectUtils.cs" />
	</ItemGroup>

	<!--<ItemGroup>
	  <ProjectReference Include="..\NativeHost.StaticLib.CLR\NativeHost.StaticLib.CLR.vcxproj" />
	</ItemGroup>-->

	<ItemGroup>
		<RuntimeHostConfigurationOption Include="System.Runtime.InteropServices.COM.LoadComponentInDefaultContext" Value="true" />
	</ItemGroup>

</Project>
