<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<RootNamespace>BD.Common8.Essentials</RootNamespace>
		<!--<AllowUnsafeBlocks>true</AllowUnsafeBlocks>-->
		<Description>具体平台的 Essentials 实现服务库</Description>
	</PropertyGroup>

	<Import Project="$(MSBuildThisFileDirectory)..\TFM_NETX_ALL.props" />

	<!-- 👇 引用 NuGet 包 #if !LINUX -->
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != ''">
		<PackageReference Include="Microsoft.Maui.Essentials" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Essentials\BD.Common8.Essentials.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Repositories.SQLitePCL\BD.Common8.Repositories.SQLitePCL.csproj" />
	</ItemGroup>

</Project>
