namespace BD.Common.Repositories.SourceGenerator.Templates;

/// <summary>
/// 仓储层实现类类型源码生成模板
/// </summary>
sealed class RepositoryImplTemplate : RepositoryTemplateBase<RepositoryImplTemplate, RepositoryImplTemplate.Metadata>
{
    public readonly record struct Metadata(
        string Namespace,
        string Summary,
        string ClassName,
        string? PrimaryKeyTypeName = null) : ITemplateMetadata
    {

    }

    protected override void WriteCore(Stream stream, object?[] args, Metadata metadata, ImmutableArray<PropertyMetadata> fields)
    {
        var format =
"""
#nullable enable
// <auto-generated/>
// ReSharper disable once CheckNamespace
namespace {0};

/// <summary>
/// {1} - 仓储层实现类
/// </summary>
public sealed partial class {2}Repository<TDbContext> : Repository<TDbContext, {2}, {3}>, I{2}Repository where TDbContext : DbContext
"""u8;
        //, IAuthenticatorDbContext
        args[0] = string.Format(args[0]!.ToString(), "Repositories");
        args[3] = fields.Single(x => x.FixedProperty == FixedProperty.Id).PropertyType;
        stream.WriteFormat(format, args);

        stream.Write(
"""

{

"""u8);

        #region 生成方法 Methods

        //WriteMethodQueryAsync(stream, metadata, fields);

        #endregion

        stream.Write(
"""
}

"""u8);
    }
}
