<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<RootNamespace>OBS</RootNamespace>
		<TargetFrameworks>net$(DotNet_Version);net8.0;net7.0;net45</TargetFrameworks>
		<Description>华为云 OBS SDK</Description>
		<Version>$(Version_HuaweiCloud_SDK_Obs)</Version>
		<FileVersion>$(Version)</FileVersion>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
		<PackageReference Include="IndexRange" />
	</ItemGroup>

	<ItemGroup>
		<None Update="README_CN.md" Pack="true" PackagePath="" Visible="false" />
		<None Update="Notice.md" Pack="true" PackagePath="" Visible="false" />
		<None Update="Help on License" Pack="true" PackagePath="" Visible="false" />
		<Compile Include="..\..\ref\huaweicloud-sdk-dotnet-obs\**\*.cs" />
	</ItemGroup>

</Project>
