name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ windows-latest ]
        os: [ aigio-win10ltsc-vm ]

    steps:
      - name: Checkout repository
#        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

#      - name: Checkout repository(BD.Git.Checkout.Tools)
#        if: ${{ matrix.os == 'aigio-win10ltsc-vm' }}
#        run: C:\actions-runner\checkout.exe ${{ github.workspace }} ${{ github.sha }} ${{ github.repositoryUrl }}

      - name: Setup .NET
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install Android SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install android

      - name: Install iOS SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install ios

      - name: Install macOS SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install macos

      - name: Install Mac Catalyst SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install maccatalyst

      - name: Install Maui
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install maui

      - name: Install wasm-tools
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install wasm-tools

      - name: Restore Workload
        run: dotnet workload restore

      - name: Verify dotnet info
        run: dotnet --info

      - name: Test
        run: dotnet test src/BD.Common.UnitTest/BD.Common.UnitTest.csproj -c Release -p:GeneratePackageOnBuild=false

  build:
    name: Build
    needs: [ test ]
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
#        os: [ windows-latest ]
        os: [ aigio-win10ltsc-vm ]
        ProjectName: [
            BD.Common,
            BD.Common.Area,
            BD.Common.BirthDate,
            BD.Common.EFCore,
            BD.Common.ModelValidator,
            BD.Common.PhoneNumber,
            BD.Common.Primitives,
            BD.Common.Primitives.ApiResponse,
            # Web UI
            BD.Common.AspNetCore.Blazor.BackManage,
            # Web API
            BD.Common.AspNetCore,
            BD.Common.AspNetCore.Identity,
            BD.Common.AspNetCore.Identity.BackManage,
            # Web API
            BD.Common.AspNetCore,
            BD.Common.AspNetCore.Identity,
            BD.Common.AspNetCore.Identity.BackManage,
            # Settings
            BD.Common.Settings,
            BD.Common.Settings.V3,
            # Server Lib
            BD.Common.SmsSender,
            # Repositories
            BD.Common.Repositories,
            BD.Common.Repositories.EFCore,
            BD.Common.Repositories.SQLitePCL,
#            BD.Common.Repositories.SourceGenerator,
#            BD.Common.Repositories.SourceGenerator.Annotations,
            # Pinyin
            BD.Common.Pinyin,
            BD.Common.Pinyin.CFStringTransform,
            BD.Common.Pinyin.ChnCharInfo,
            BD.Common.Pinyin.TinyPinyin,
            # Essentials
            BD.Common.Essentials,
            BD.Common.Essentials.Primitives,
            BD.Common.Essentials.Utils,
            BD.Common.Essentials.Maui,
            BD.Common.Essentials.Maui.Runtime,
            BD.Common.Essentials.Xamarin,
            BD.Common.Essentials.Preferences.DBreeze,
            BD.Common.Essentials.Preferences.SQLite,
            # Client Lib
            BD.Common.Mvvm,
            BD.Common.Mvvm.ReactiveUI,
            BD.Common.Navigation,
            BD.Common.Security,
            BD.Common.Toast,
          ]

    steps:
      - name: Checkout repository
#        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

#      - name: Checkout repository(BD.Git.Checkout.Tools)
#        if: ${{ matrix.os == 'aigio-win10ltsc-vm' }}
#        run: C:\actions-runner\checkout.exe ${{ github.workspace }} ${{ github.sha }} ${{ github.repositoryUrl }}

      - name: Setup .NET
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install Android SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install android

      - name: Install iOS SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install ios

      - name: Install macOS SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install macos

      - name: Install Mac Catalyst SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install maccatalyst

      - name: Install Maui
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install maui

      - name: Install wasm-tools
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install wasm-tools

      - name: Restore Workload
        run: dotnet workload restore

      - name: Verify dotnet info
        run: dotnet --info

      - name: Build
        run: dotnet build -c Release src\${{ matrix.ProjectName }}\${{ matrix.ProjectName }}.csproj

      - name: Push nuget packages
        run: |
          dotnet nuget push pkg\${{ matrix.ProjectName }}*.nupkg -s https://nuget.pkg.github.com/BeyondDimension -k ${{ secrets.RMBADMIN_TOKEN }} --skip-duplicate
          dotnet nuget push pkg\${{ matrix.ProjectName }}*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
          dotnet nuget push pkg\${{ matrix.ProjectName }}*.snupkg -s https://nuget.pkg.github.com/BeyondDimension -k ${{ secrets.RMBADMIN_TOKEN }} --skip-duplicate
          dotnet nuget push pkg\${{ matrix.ProjectName }}*.snupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      - name: Delete nuget packages
        if: ${{ matrix.os == 'aigio-win10ltsc-vm' }}
        shell: cmd
        run: del pkg /f /q

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Changelog
        uses: glennawatson/ChangeLog@v1
        id: changelog

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.RMBADMIN_TOKEN }}
          body: ${{ steps.changelog.outputs.commitLog }}
          draft: false
          prerelease: false
